# Generated by Django 2.2.3 on 2019-07-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, unique=True, verbose_name='password'),
        ),
    ]
