# Generated by Django 2.2.3 on 2019-07-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20190726_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=70, unique=True, verbose_name='username'),
        ),
    ]
