# Generated by Django 2.2.3 on 2019-07-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20190729_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=500, verbose_name='password'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
