# Generated by Django 2.2.3 on 2019-07-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20190729_2020'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='_user',
        ),
    ]
